import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Archive, CheckCircle2, Files, Plus, Search, Trash2, UploadCloud } from 'lucide-react';
import toast from 'react-hot-toast';
import { api } from '../lib/api';
import EmptyState from '../components/EmptyState';

export default function DocumentsPage() {
  const [q, setQ] = useState(''); const [status, setStatus] = useState('');
  const [data, setData] = useState(null); const [updatingId, setUpdatingId] = useState('');
  async function load() { setData(await api(`/documents?page=1&limit=30&sort=updated${status ? `&status=${status}` : ''}${q ? `&q=${encodeURIComponent(q)}` : ''}`)); }
  useEffect(() => { const timer = setTimeout(() => load().catch(error => toast.error(error.message)), 200); return () => clearTimeout(timer); }, [q, status]);
  async function changeStatus(document, nextStatus) { setUpdatingId(document._id); try { await api(`/documents/${document._id}/status`, { method: 'PATCH', body: { status: nextStatus } }); toast.success(`Document marked ${nextStatus}`); await load(); } catch (error) { toast.error(error.message); } finally { setUpdatingId(''); } }
  async function removeDocument(document) {
    const confirmed = window.confirm(`Permanently delete “${document.title}”?\n\nThis also deletes its versions, AI analysis, vector chunks, related share links, and document-chat history. This cannot be undone.`);
    if (!confirmed) return;
    setUpdatingId(document._id);
    try { await api(`/documents/${document._id}`, { method: 'DELETE' }); toast.success('Document and related data permanently deleted'); await load(); } catch (error) { toast.error(error.message); } finally { setUpdatingId(''); }
  }
  return <div className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm font-black text-indigo-500">DOCUMENT VAULT</div><h1 className="mt-1 text-3xl font-black tracking-tight">My documents</h1><p className="mt-2 text-sm text-slate-500">Private drafts, uploads, analyses and version history.</p></div><div className="flex gap-2"><Link className="btn btn-secondary" to="/app/upload"><UploadCloud size={16}/> Upload</Link><Link className="btn btn-primary" to="/app/templates"><Plus size={16}/> Create</Link></div></div>
    <div className="panel p-4"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search size={18} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"/><input className="input has-search-icon" value={q} onChange={event => setQ(event.target.value)} placeholder="Search titles and tags…"/></div><select className="input md:w-52" value={status} onChange={event => setStatus(event.target.value)}><option value="">All statuses</option><option value="draft">Draft</option><option value="completed">Completed</option><option value="archived">Archived</option></select></div></div>
    {data?.items?.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.items.map(document => <article key={document._id} className="panel p-5"><Link to={`/app/documents/${document._id}`} className="block group"><div className="flex items-start justify-between"><div className="stat-icon"><Files size={19}/></div><span className={`badge ${document.status === 'completed' ? 'badge-green' : document.status === 'archived' ? 'badge-amber' : 'badge-indigo'}`}>{document.status}</span></div><h3 className="mt-5 truncate font-black group-hover:text-indigo-500">{document.title}</h3><div className="mt-2 text-xs capitalize text-slate-500">{document.documentType.replace(/-/g, ' ')}</div><div className="mt-4 text-xs font-semibold text-slate-400">Version {document.currentVersion} · {new Date(document.updatedAt).toLocaleDateString()}</div></Link><div className="mt-4 flex flex-wrap gap-2 border-t border-slate-100 pt-4 dark:border-slate-800">{document.status !== 'completed' && <button className="btn btn-secondary py-2 text-xs" disabled={updatingId === document._id} onClick={() => changeStatus(document, 'completed')}><CheckCircle2 size={14}/> Complete</button>}{document.status !== 'archived' && <button className="btn btn-secondary py-2 text-xs" disabled={updatingId === document._id} onClick={() => changeStatus(document, 'archived')}><Archive size={14}/> Archive</button>}{document.status === 'archived' && <button className="btn btn-secondary py-2 text-xs" disabled={updatingId === document._id} onClick={() => changeStatus(document, 'draft')}>Restore draft</button>}<button className="btn btn-secondary py-2 text-xs text-rose-600 hover:border-rose-300 hover:bg-rose-50 dark:text-rose-400" disabled={updatingId === document._id} onClick={() => removeDocument(document)}><Trash2 size={14}/> Delete</button></div></article>)}</div> : data ? <EmptyState title={status === 'archived' ? 'No archived documents' : 'No documents found'} text={q ? 'Try a different search.' : 'Your secure document vault is empty.'} action={<Link className="btn btn-primary" to="/app/templates">Create document</Link>}/> : <div className="panel p-8"><div className="spinner"/></div>}
  </div>;
}
