import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeft, FileCheck2, Sparkles } from 'lucide-react';
import { api } from '../lib/api';
import LegalNotice from '../components/LegalNotice';

export default function GeneratePage() {
  const { templateId } = useParams(); const navigate = useNavigate();
  const [templates, setTemplates] = useState(null); const [loadError, setLoadError] = useState(''); const [fields, setFields] = useState({}); const [language, setLanguage] = useState('en'); const [loading, setLoading] = useState(false); const [preview, setPreview] = useState('');
  useEffect(() => { api('/documents/templates').then(result => setTemplates(result.templates)).catch(error => { setLoadError(error.message); setTemplates([]); }); }, []);
  const template = useMemo(() => templates?.find(item => item.id === templateId), [templates, templateId]);
  async function submit(event) { event.preventDefault(); setLoading(true); try { const result = await api('/documents/generate', { method: 'POST', body: { templateId, fields, language, save: true } }); setPreview(result.content); toast.success('Draft created'); if (result.document?._id) setTimeout(() => navigate(`/app/documents/${result.document._id}`), 500); } catch (error) { toast.error(error.details?.join?.(', ') || error.message); } finally { setLoading(false); } }
  if (templates === null) return <div className="panel p-8">Loading template…</div>;
  if (!template) return <div className="panel p-8 text-center"><h1 className="text-lg font-black">Template unavailable</h1><p className="mt-2 text-sm text-slate-500">{loadError || 'This template does not exist or may have been removed.'}</p><Link to="/app/templates" className="btn btn-primary mt-5">Browse templates</Link></div>;
  return <div className="space-y-5"><Link to="/app/templates" className="inline-flex items-center gap-1 text-sm font-bold text-slate-500 hover:text-indigo-500"><ArrowLeft size={15}/> Templates</Link><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="badge badge-indigo">{template.category}</span><h1 className="mt-2 text-3xl font-black tracking-tight">{template.name}</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">{template.description}</p></div></div><LegalNotice/><div className="grid gap-6 xl:grid-cols-[.78fr_1.22fr]"><form onSubmit={submit} className="panel h-fit p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><div className="stat-icon"><FileCheck2 size={20}/></div><div><div className="font-black">Document details</div><div className="text-xs text-slate-500">Complete the required fields to create your draft.</div></div></div><div className="grid gap-4 sm:grid-cols-2">{template.fields.map(field => <div key={field.name} className={field.type === 'textarea' ? 'sm:col-span-2' : ''}><label className="label">{field.label} {field.required && <span className="text-rose-500">*</span>}</label>{field.type === 'textarea' ? <textarea className="input min-h-24" required={field.required} value={fields[field.name] || ''} onChange={event => setFields({ ...fields, [field.name]: event.target.value })}/> : <input className="input" type={field.type} required={field.required} value={fields[field.name] || ''} onChange={event => setFields({ ...fields, [field.name]: field.type === 'number' && event.target.value !== '' ? Number(event.target.value) : event.target.value })}/>}</div>)}</div><div className="mt-4"><label className="label">Document language</label><select className="input" value={language} onChange={event => setLanguage(event.target.value)}><option value="en">English</option><option value="hi">Hindi</option></select></div><button className="btn btn-primary mt-5 w-full" disabled={loading}>{loading ? <><span className="spinner h-4 w-4 border-2 border-white/40 border-t-white"/> Creating…</> : <><Sparkles size={16}/> Create draft</>}</button></form><div className="panel p-3 sm:p-5"><div className="mb-3 px-2"><div className="text-sm font-black">Document preview</div><div className="text-xs text-slate-400">Your draft will appear here before the workspace opens.</div></div><div className="doc-paper">{preview || `Your ${template.name} draft will appear here.`}</div></div></div></div>;
}
