import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { ArrowLeft, FileCheck2, LockKeyhole, Sparkles } from 'lucide-react';
import { api } from '../lib/api';
import LegalNotice from '../components/LegalNotice';

export default function GuestDraftPage() {
  const navigate = useNavigate(); const [templates, setTemplates] = useState([]); const [templateId, setTemplateId] = useState('rent-agreement'); const [fields, setFields] = useState({}); const [preview, setPreview] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { api('/public/guest/templates', { auth: false }).then(result => setTemplates(result.templates)).catch(error => toast.error(error.message)); }, []);
  const template = useMemo(() => templates.find(item => item.id === templateId), [templates, templateId]);
  async function draft(event) { event.preventDefault(); if (!template) return; setLoading(true); try { const result = await api('/public/guest/draft-preview', { method: 'POST', body: { templateId, fields, language: 'en' }, auth: false }); setPreview(result.content); toast.success('Draft generated successfully'); } catch (error) { toast.error(error.details?.join?.(', ') || error.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-app p-5"><div className="mx-auto max-w-6xl space-y-6 py-4"><Link to="/" className="inline-flex items-center gap-1 text-sm font-bold text-slate-500 hover:text-indigo-500"><ArrowLeft size={15}/> Back to home</Link><div><div className="text-sm font-black text-indigo-500">DOCUMENT DRAFTING</div><h1 className="mt-1 text-3xl font-black">Create a draft</h1><p className="mt-2 text-sm text-slate-500">Select a template and customize the fields to generate a compliant legal draft.</p></div><LegalNotice/><div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><form onSubmit={draft} className="panel p-6"><div className="flex items-center gap-2 font-black"><FileCheck2 size={18} className="text-indigo-500"/> Draft details</div><label className="label mt-5">Document type</label><select className="input" value={templateId} onChange={event => { setTemplateId(event.target.value); setFields({}); }}><option value="">Choose a template</option>{templates.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{template && <div className="mt-4 grid gap-4">{template.fields.map(field => <div key={field.name}><label className="label">{field.label} {field.required && <span className="text-rose-500">*</span>}</label>{field.type === 'textarea' ? <textarea className="input min-h-24" required={field.required} value={fields[field.name] || ''} onChange={event => setFields({ ...fields, [field.name]: event.target.value })}/> : <input className="input" type={field.type} required={field.required} value={fields[field.name] || ''} onChange={event => setFields({ ...fields, [field.name]: event.target.value })}/>}</div>)}</div>}<button className="btn btn-primary mt-5 w-full" disabled={!template || loading}><Sparkles size={16}/>{loading ? 'Generating draft…' : 'Generate draft'}</button></form><section className="panel p-6"><div className="font-black">Draft preview</div>{preview ? <><div className="doc-paper mt-4 whitespace-pre-wrap">{preview}</div><button className="btn btn-primary mt-5 w-full" onClick={() => navigate('/register', { state: { guestAction: 'export or save this draft' } })}><LockKeyhole size={16}/> Save or export draft</button></> : <p className="mt-4 text-sm text-slate-500">Fill in the document fields on the left to generate and inspect your draft.</p>}</section></div></div></main>;
}
