import { ArrowRight, CheckCircle2, FileText, GitCompareArrows, LockKeyhole, Mail, MessageSquareQuote, SearchCheck, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import Logo from '../components/Logo';
import LegalNotice from '../components/LegalNotice';

const features = [
  [FileText, 'Document drafting', 'Create editable legal drafts from guided forms or your own document requirements.'],
  [SearchCheck, 'Document review', 'Upload and review important dates, obligations, financial terms and missing details.'],
  [MessageSquareQuote, 'Document questions', 'Ask questions about your uploaded documents and view the relevant references.'],
  [GitCompareArrows, 'Version history', 'Keep a clear record of changes and compare document versions.'],
  [LockKeyhole, 'Private workspace', 'Your documents stay organised in your own secure workspace.'],
  [ShieldCheck, 'Exports and sharing', 'Download documents as PDF or DOCX, or share a time-limited read-only link.']
];

export default function LandingPage() {
  return <div className="min-h-screen bg-white text-slate-950 dark:bg-slate-950 dark:text-white">
    <header className="sticky top-0 z-20 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex max-w-7xl items-center px-5 py-4"><Link to="/"><Logo/></Link><nav className="ml-auto flex items-center gap-2"><Link className="btn btn-secondary hidden sm:inline-flex" to="/login">Sign in</Link><Link className="btn btn-primary" to="/register">Get started <ArrowRight size={16}/></Link></nav></div></header>
    <main><section className="relative overflow-hidden"><div className="hero-grid absolute inset-0 opacity-80"/><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.08fr_.92fr] lg:py-28"><div><div className="mb-5 inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-bold text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/50 dark:text-indigo-300">LEGAL DOCUMENT WORKSPACE</div><h1 className="max-w-4xl text-5xl font-black leading-[1.03] tracking-[-.04em] sm:text-6xl">Create, understand and manage <span className="gradient-text">legal documents.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">LexSahayak brings drafting, document review, version history, exports and private sharing into one simple workspace.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn btn-primary px-5 py-3" to="/register">Open workspace <ArrowRight size={17}/></Link><a className="btn btn-secondary px-5 py-3" href="#features">Explore features</a></div><div className="mt-8 grid max-w-xl gap-2 text-sm text-slate-600 sm:grid-cols-2 dark:text-slate-400">{['Guided document forms', 'Private document storage', 'PDF & DOCX export', 'Version comparison'].map(item => <div className="flex items-center gap-2" key={item}><CheckCircle2 size={16} className="text-emerald-500"/>{item}</div>)}</div></div><div className="panel p-5 sm:p-7"><div className="text-xs font-bold uppercase tracking-[.18em] text-slate-400">Document overview</div><div className="mt-1 text-xl font-black">Employment Agreement</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-4 dark:bg-emerald-950/25"><div className="text-xs font-bold text-emerald-700 dark:text-emerald-400">Document details</div><div className="mt-2 text-sm">Parties<br/>Salary<br/>Start date<br/>Notice period</div></div><div className="rounded-2xl bg-amber-50 p-4 dark:bg-amber-950/25"><div className="text-xs font-bold text-amber-700 dark:text-amber-400">Review points</div><div className="mt-2 text-sm">IP ownership<br/>Remote work terms<br/>Dispute handling</div></div></div><div className="mt-4 rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck size={16} className="text-indigo-500"/> Relevant document reference</div><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">“The notice period is 30 days...” <span className="font-bold text-indigo-500">[S1]</span></p></div></div></div></section>
    <section id="features" className="mx-auto max-w-7xl px-5 py-20"><div className="max-w-2xl"><div className="text-sm font-black uppercase tracking-[.2em] text-indigo-500">ALL IN ONE PLACE</div><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A complete legal-document workspace.</h2><p className="mt-4 text-slate-600 dark:text-slate-400">Everything you need to prepare, review, store and share your documents with confidence.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text]) => <div className="feature-card dark:border-slate-800 dark:bg-slate-900/70" key={title}><div className="stat-icon mb-4"><Icon size={20}/></div><h3 className="font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{text}</p></div>)}</div></section>
    <section className="mx-auto max-w-4xl px-5 py-10"><LegalNotice/></section></main>
    <footer className="border-t border-slate-200 px-5 py-8 text-center text-xs text-slate-500 dark:border-slate-800"><div>LexSahayak · Legal document workspace</div><a className="mt-2 inline-flex items-center gap-1 font-semibold text-indigo-500" href="mailto:s85319748@gmail.com"><Mail size={13}/> Contact: s85319748@gmail.com</a></footer>
  </div>;
}
