import { useState } from 'react';
import toast from 'react-hot-toast';
import { BookOpenCheck, MessageSquareText, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api';
import LegalNotice from '../components/LegalNotice';

export default function LegalChatPage() {
  const [messages, setMessages] = useState([{ role: 'assistant', content: 'Ask a question about the available legal reference materials.' }]);
  const [q, setQ] = useState(''); const [conversationId, setConversationId] = useState(); const [loading, setLoading] = useState(false);
  async function send(event) { event.preventDefault(); if (!q.trim()) return; const question = q; setQ(''); setMessages(items => [...items, { role: 'user', content: question }]); setLoading(true); try { const result = await api('/chat', { method: 'POST', body: { question, conversationId } }); setConversationId(result.conversationId); setMessages(items => [...items, { role: 'assistant', content: result.answer, citations: result.citations }]); } catch (error) { toast.error(error.message); } finally { setLoading(false); } }
  return <div className="space-y-6"><div><div className="text-sm font-black text-indigo-500">LEGAL REFERENCES</div><h1 className="mt-1 text-3xl font-black tracking-tight">Legal reference chat</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Find information from the reference materials available in this workspace.</p></div><LegalNotice/><div className="grid gap-6 xl:grid-cols-[1fr_320px]"><div className="panel overflow-hidden"><div className="border-b border-slate-200 p-4 dark:border-slate-800"><div className="flex items-center gap-2 font-black"><MessageSquareText size={18} className="text-indigo-500"/> Reference assistant</div></div><div className="min-h-[500px] space-y-4 p-4 sm:p-6">{messages.map((message, index) => <div key={index} className={`chat-bubble ${message.role === 'user' ? 'chat-user' : 'chat-ai'}`}>{message.content}{message.citations?.length > 0 && <div className="mt-3 border-t border-slate-300/30 pt-2 text-[11px]"><b>References used</b>{message.citations.map(citation => <div key={citation.chunkId} className="mt-1">[{citation.label}] {citation.citation || 'Reference material'}</div>)}</div>}</div>)}{loading && <div className="chat-bubble chat-ai">Searching references…</div>}</div><form onSubmit={send} className="flex gap-2 border-t border-slate-200 p-4 dark:border-slate-800"><input className="input" value={q} onChange={event => setQ(event.target.value)} placeholder="Ask a legal reference question…"/><button className="btn btn-primary" disabled={loading}>Ask</button></form></div><aside className="space-y-4"><div className="panel p-5"><div className="flex items-center gap-2 font-black"><BookOpenCheck size={18} className="text-indigo-500"/> How it works</div><ol className="mt-4 space-y-3 text-sm leading-6 text-slate-500"><li><b>1.</b> Enter your question.</li><li><b>2.</b> Relevant reference material is checked.</li><li><b>3.</b> The response includes references where available.</li></ol></div><div className="panel p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-emerald-500"/> Keep in mind</div><p className="mt-2 text-sm leading-6 text-slate-500">Check current official sources and obtain professional advice for important matters.</p></div></aside></div></div>;
}
