import { useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { FileText, ScanSearch, ShieldCheck, UploadCloud, X } from 'lucide-react';
import { api } from '../lib/api';
import LegalNotice from '../components/LegalNotice';

export default function UploadPage() {
  const input = useRef(); const navigate = useNavigate();
  const [file, setFile] = useState(null); const [title, setTitle] = useState(''); const [loading, setLoading] = useState(false);
  function select(selected) { if (!selected) return; setFile(selected); if (!title) setTitle(selected.name.replace(/\.[^.]+$/, '')); }
  async function upload() { if (!file) return toast.error('Choose a document first'); const body = new FormData(); body.append('file', file); if (title) body.append('title', title); setLoading(true); try { const result = await api('/documents/upload', { method: 'POST', body }); toast.success('Document parsed securely'); navigate(`/app/documents/${result.document._id}`); } catch (error) { toast.error(error.message); } finally { setLoading(false); } }
  return <div className="space-y-6">
    <div><div className="text-sm font-black text-indigo-500">SECURE ANALYZER</div><h1 className="mt-1 text-3xl font-black tracking-tight">Upload a legal document</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">PDF, DOCX, TXT, JPG and PNG files are safely validated. Scanned PDFs and document photos use OCR to extract readable text.</p></div>
    <LegalNotice/>
    <div className="grid gap-6 xl:grid-cols-[1fr_.65fr]"><div className="panel p-5 sm:p-7"><input ref={input} className="hidden" type="file" accept=".pdf,.docx,.txt,.jpg,.jpeg,.png" onChange={event => select(event.target.files?.[0])}/><button type="button" onClick={() => input.current?.click()} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); select(event.dataTransfer.files?.[0]); }} className="grid min-h-72 w-full place-items-center rounded-3xl border-2 border-dashed border-slate-200 bg-slate-50/70 p-8 text-center transition hover:border-indigo-300 hover:bg-indigo-50/50 dark:border-slate-700 dark:bg-slate-900/50 dark:hover:border-indigo-700"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-indigo-100 text-indigo-600 dark:bg-indigo-950/60 dark:text-indigo-300"><UploadCloud size={28}/></div><h3 className="mt-4 text-lg font-black">Drop a document or scan here</h3><p className="mt-2 text-sm text-slate-500">PDF, DOCX, TXT, JPG or PNG. Maximum size is controlled by the backend (8 MB by default).</p></div></button>{file && <div className="mt-4 flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-slate-800"><div className="stat-icon"><FileText size={18}/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{file.name}</div><div className="text-xs text-slate-400">{(file.size / 1024 / 1024).toFixed(2)} MB</div></div><button className="icon-btn" onClick={() => setFile(null)}><X size={17}/></button></div>}<div className="mt-4"><label className="label">Workspace title</label><input className="input" value={title} onChange={event => setTitle(event.target.value)} placeholder="Optional custom title"/></div><button className="btn btn-primary mt-4 w-full" onClick={upload} disabled={!file || loading}>{loading ? 'Parsing and running OCR…' : <><ScanSearch size={17}/> Add to workspace</>}</button></div>
      <div className="space-y-4"><div className="panel p-5"><div className="flex items-center gap-2 font-black"><ShieldCheck size={18} className="text-emerald-500"/> Upload safeguards</div><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-500"><li>• MIME allowlist and file-signature validation</li><li>• OCR is limited to five PDF pages by default</li><li>• Uploaded files are never executed</li><li>• User ownership is applied before indexing</li></ul></div><div className="panel p-5"><div className="font-black">Scanned document?</div><p className="mt-2 text-sm leading-6 text-slate-500">Use a clear, upright JPG/PNG or scanned PDF. OCR accuracy depends on image quality; always review extracted text before relying on it.</p></div></div>
    </div>
  </div>;
}
