import { Router } from 'express';
import { asyncHandler } from '../utils/asyncHandler.js';
import { requireAuth } from '../middleware/auth.js';
import { aiLimiter, uploadLimiter } from '../middleware/rateLimits.js';
import { documentUpload } from '../middleware/upload.js';
import { validate } from '../middleware/validate.js';
import { generateSchema, updateDocumentSchema, updateStatusSchema, idParamSchema, listDocumentsSchema, clauseSchema, analyzeSchema, compareSchema, exportSchema, shareSchema } from '../validators/documentSchemas.js';
import { templates, generate, uploadAndCreate, list, getOne, update, updateStatus, analyze, clause, versions, compare, exportDocument, archive, remove, createShareLink, addSignature, removeSignature, addComment, updateComment, removeComment, addMilestone, updateMilestone, removeMilestone } from '../controllers/documentController.js';
const r=Router(); r.use(requireAuth);
r.get('/templates',asyncHandler(templates));
r.post('/generate',aiLimiter,validate(generateSchema),asyncHandler(generate));
r.post('/upload',uploadLimiter,documentUpload.single('file'),asyncHandler(uploadAndCreate));
r.get('/',validate(listDocumentsSchema),asyncHandler(list));
r.post('/clause',aiLimiter,validate(clauseSchema),asyncHandler(clause));
r.get('/:id',validate(idParamSchema),asyncHandler(getOne));
r.patch('/:id/status',validate(updateStatusSchema),asyncHandler(updateStatus));
r.patch('/:id',validate(updateDocumentSchema),asyncHandler(update));
r.delete('/:id',validate(idParamSchema),asyncHandler(remove));
r.post('/:id/analyze',aiLimiter,validate(analyzeSchema),asyncHandler(analyze));
r.get('/:id/versions',validate(idParamSchema),asyncHandler(versions));
r.get('/:id/compare',validate(compareSchema),asyncHandler(compare));
r.get('/:id/export/:format',validate(exportSchema),asyncHandler(exportDocument));
r.post('/:id/archive',validate(idParamSchema),asyncHandler(archive));
r.post('/:id/share',validate(shareSchema),asyncHandler(createShareLink));
r.post('/:id/signatures',validate(idParamSchema),asyncHandler(addSignature));
r.delete('/:id/signatures/:signatureId',validate(idParamSchema),asyncHandler(removeSignature));
r.post('/:id/comments',validate(idParamSchema),asyncHandler(addComment));
r.patch('/:id/comments/:commentId',validate(idParamSchema),asyncHandler(updateComment));
r.delete('/:id/comments/:commentId',validate(idParamSchema),asyncHandler(removeComment));
r.post('/:id/milestones',validate(idParamSchema),asyncHandler(addMilestone));
r.patch('/:id/milestones/:milestoneId',validate(idParamSchema),asyncHandler(updateMilestone));
r.delete('/:id/milestones/:milestoneId',validate(idParamSchema),asyncHandler(removeMilestone));
export default r;
