import { Router } from 'express';
import { asyncHandler } from '../utils/asyncHandler.js';
import { validate } from '../middleware/validate.js';
import { publicShareSchema } from '../validators/documentSchemas.js';
import { publicShared } from '../controllers/documentController.js';
import { guestDraftPreview, guestTemplates, guestUploadPreview } from '../controllers/guestController.js';
import { documentUpload } from '../middleware/upload.js';
import { aiLimiter, uploadLimiter } from '../middleware/rateLimits.js';
const r=Router();
r.get('/share/:token',validate(publicShareSchema),asyncHandler(publicShared));
r.get('/guest/templates',asyncHandler(guestTemplates));
r.post('/guest/draft-preview',aiLimiter,asyncHandler(guestDraftPreview));
r.post('/guest/upload-preview',uploadLimiter,documentUpload.single('file'),asyncHandler(guestUploadPreview));
export default r;
